#!/bin/sh

if [ "$1" == "" ]; then
ARCHOS=i686_linux
else
ARCHOS=$1
fi

echo "Setting up directories for $ARCHOS system"
echo
echo "If you want to compile for a different system, type"
echo "   setup archos"
echo "where archos is the architecture of the system e.g. 'setup hp_ux10'"
echo
echo "Do not forget to edit the Makefile and change the ARCHOS including system"
echo "specific variables CC, CLAGS, DEBUGFLAGS, OPTFLAGS, DEFINES and LDFLAGS"

mkdir -p obj/$ARCHOS-d
mkdir -p obj/$ARCHOS
mkdir -p lib/$ARCHOS

