#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include "MSTK.h"


#ifdef __cplusplus
extern "C" {
#endif
  /* 
     This function builds the partition boundary for the submesh.
     All faces(surface mesh) or regions(volume mesh) are marked 
     as PINTERIOR, processor boundary vertices/edges/faces
     are marked as PBOUNDARY. 

     Submesh is a subset of mesh generated by MESH_Partition()
     To add PGHOST entities and mark POVERLAP, call MESH_AddGHOST().
 
     Author(s): Duo Wang, Rao Garimella
  */

int MESH_Surf_BuildPBoundary(Mesh_ptr mesh, Mesh_ptr submesh);
int MESH_Vol_BuildPBoundary(Mesh_ptr mesh, Mesh_ptr submesh);

int MESH_BuildPBoundary(Mesh_ptr mesh, Mesh_ptr submesh ) {
  int nf, nr;
  /* basic mesh information */
  nf = MESH_Num_Faces(mesh);
  nr = MESH_Num_Regions(mesh);
 
  if (nr) 
    MESH_Vol_BuildPBoundary(mesh, submesh);
  else if(nf) 
    MESH_Surf_BuildPBoundary(mesh, submesh);
  else {
    MSTK_Report("MESH_BuildPBoundary()","This is not a valid mstk file",MSTK_ERROR);
    exit(-1);
  }
  return 1;
}
  
int MESH_Surf_BuildPBoundary(Mesh_ptr mesh, Mesh_ptr submesh) {
  int idx, vertex_gid, edge_gid;
  MVertex_ptr gmv,lmv;
  MEdge_ptr lme, gme;
  MFace_ptr lmf, gmf;
  List_ptr lmvfaces, gmvfaces, lmefaces, gmefaces;
  MAttrib_ptr l2gatt;

  l2gatt = MESH_AttribByName(submesh,"Local2Global");

  /* Mark all the face to be interior */
  idx = 0;
  while((lmf = MESH_Next_Face(submesh,&idx)))  
    MF_Set_PType(lmf,PINTERIOR);
  
  /* Loop through edges */
  idx = 0;
  while((lme = MESH_Next_Edge(submesh,&idx))) {
    MEnt_Get_AttVal(lme,l2gatt,0,0,&gme);
    if (!gme)
      MSTK_Report("MESH_BuildPBoundary","Cannot find global edge of local edge",MSTK_ERROR);
      

    lmefaces = ME_Faces(lme);
    gmefaces = ME_Faces(gme);

    /* if the number of neighbor faces is different, it is a boundary edge */
    if(List_Num_Entries(lmefaces) != List_Num_Entries(gmefaces))
      ME_Set_PType(lme,PBOUNDARY);
    else
      ME_Set_PType(lme,PINTERIOR);
    List_Delete(lmefaces);
    List_Delete(gmefaces);
  }




  /* Loop through vertices */
  idx = 0;
  while((lmv = MESH_Next_Vertex(submesh,&idx))) {
    MEnt_Get_AttVal(lmv,l2gatt,0,0,&gmv);
    if (!gmv)
      MSTK_Report("MESH_BuildPBoundary","Cannot find global vertex of local vertex",MSTK_ERROR);

    lmvfaces = MV_Faces(lmv);
    gmvfaces = MV_Faces(gmv);
    /* if the number of neighbor faces is different, it is a boundary vertex */
    if(List_Num_Entries(lmvfaces) != List_Num_Entries(gmvfaces))
      MV_Set_PType(lmv,PBOUNDARY);
    else
      MV_Set_PType(lmv,PINTERIOR);
    List_Delete(lmvfaces);
    List_Delete(gmvfaces);
  }

  return 1;
}



int MESH_Vol_BuildPBoundary(Mesh_ptr mesh, Mesh_ptr submesh) {
  int idx, vertex_gid, edge_gid, face_gid;
  MVertex_ptr gmv,lmv;
  MEdge_ptr lme, gme;
  MFace_ptr lmf, gmf;
  MRegion_ptr lmr, gmr;
  List_ptr lmvregs, gmvregs;
  List_ptr lmeregs, gmeregs;
  List_ptr lmfregs, gmfregs;
  MAttrib_ptr l2gatt;


  l2gatt = MESH_AttribByName(submesh,"Local2Global");

  /* Mark all the regions to be interior */
  idx = 0;
  while((lmr = MESH_Next_Region(submesh,&idx)))  
    MR_Set_PType(lmr,PINTERIOR);
  

  /* Loop through faces */
  idx = 0;
  while((lmf = MESH_Next_Face(submesh,&idx))) {
    MEnt_Get_AttVal(lmf,l2gatt,0,0,&gmf);
    if (!gmf)
      MSTK_Report("MESH_BuildPBoundary","Cannot find global vertex of local vertex",MSTK_ERROR);

    lmfregs = MF_Regions(lmf);
    gmfregs = MF_Regions(gmf);

    /* if the number of neighbor regions is different, it is a boundary face */
    if(List_Num_Entries(lmfregs) != List_Num_Entries(gmfregs))
      MF_Set_PType(lmf,PBOUNDARY);
    else
      MF_Set_PType(lmf,PINTERIOR);
    List_Delete(lmfregs);
    List_Delete(gmfregs);
  }

  /* Loop through edges */
  idx = 0;
  while((lme = MESH_Next_Edge(submesh,&idx))) {
    MEnt_Get_AttVal(lme,l2gatt,0,0,&gme);
    if (!gme)
      MSTK_Report("MESH_BuildPBoundary","Cannot find global edge of local edge",MSTK_ERROR);

    lmeregs = ME_Regions(lme);
    gmeregs = ME_Regions(gme);

    /* if the number of neighbor faces is different, it is a boundary edge */
    if(List_Num_Entries(lmeregs) != List_Num_Entries(gmeregs))
      ME_Set_PType(lme,PBOUNDARY);
    else
      ME_Set_PType(lme,PINTERIOR);
    List_Delete(lmeregs);
    List_Delete(gmeregs);
  }


  /* Loop through vertices */
  idx = 0;
  while((lmv = MESH_Next_Vertex(submesh,&idx))) {
    MEnt_Get_AttVal(lmv,l2gatt,0,0,&gmv);
    if (!gmv)
      MSTK_Report("MESH_BuildPBoundary","Cannot find global vertex of local vertex",MSTK_ERROR);

    lmvregs = MV_Regions(lmv);
    gmvregs = MV_Regions(gmv);
    /* if the number of neighbor regions is different, it is a boundary vertex */
    if(List_Num_Entries(lmvregs) != List_Num_Entries(gmvregs))
      MV_Set_PType(lmv,PBOUNDARY);
    else
      MV_Set_PType(lmv,PINTERIOR);
    List_Delete(lmvregs);
    List_Delete(gmvregs);
  }

  return 1;
}

  
#ifdef __cplusplus
}
#endif

