#!/bin/bash

#
# Driver file for building MSTK
# 
# -D CMAKE_BUILD_TYPE:STRING=Debug          - for debug library
#                            Release        - for optimized library
#                            RelWithDebInfo - optimized with debug symbols
#                            MinSizeRel     - for min size optimized library
#
# Top-level directory in which to install library and include files e.g.
#
# -D INSTALL_DIR:FILEPATH=/usr/local/packages
#
# Add version number to the library (libmstk-1.8.a instead of libmstk.a)
#
# -D INSTALL_ADD_VERSION=yes|no
#
# Support for parallel meshes
# 
# -D ENABLE_PARALLEL=yes|no  (default is yes)
#
# Must define path to Metis
#
#
# Support for importing/exporting ExodusII file
#
# -D ENABLE_ExodusII=yes|no (default is yes)
#
# Must define path to ExodusII and NetCDF packages
# 
# -D ExodusII_DIR:FILEPATH="/usr/packages/exodusii/"
# -D NetCDF_DIR:FILEPATH="/usr/packages/netcdf-4.0/"
#
#
# -D ENABLE_Tests=yes|no (default is yes)
#
# If tests are enabled then path to UnitTest++ has to be specified
#
# If cmake is unable to find an include file because it is in an unusual
# place and not PKGNAME_DIR/include, then you can add a line to this
# script specifying PKGNAME_INCLUDE_DIR like so
#
#  -D Curl_INCLUDE_DIR:FILEPATH=/usr/local/lib/cmcurl/src/incs
#
# You can similarly force it to find a library in a particular location
# by specifying PKGNAME_LIB_DIR
#
# Note that PKGNAME must be specified EXACTLY as it was specified for 
# the PKGNAME_DIR variable, i.e, if the script uses Curl_DIR, then
# the additional path has to be Curl_INCLUDE_DIR and not CURL_INCLUDE_DIR
#
# Rao Garimella (rao@lanl.gov)



# Define platform 

ARCH=`uname -m`
OS=`uname -s`
ARCHOS=${ARCH}_${OS}


# Top level directory where the code lives

SOURCE=$HOME/develop/mstk/1.81dev



# Clear out old junk

rm -f CMakeCache.txt


# modify the paths that point to the location of the
# installation directories below

/usr/bin/cmake \
  -D CMAKE_BUILD_TYPE:STRING=Debug \
  -D CMAKE_C_COMPILER:FILEPATH="gcc" \
  -D CMAKE_CXX_COMPILER:FILEPATH="g++" \
  -D ENABLE_PARALLEL=no \
  -D ENABLE_ExodusII=no \
  -D ENABLE_Tests=no \
  -D INSTALL_DIR:FILEPATH=${SOURCE} \
  -D INSTALL_ADD_VERSION=no \
  ${SOURCE} 

