#!/bin/bash

#
# Driver file for building MSTK
# 
# -D CMAKE_BUILD_TYPE:STRING=Debug          - for debug library
#                            Release        - for optimized library
#                            RelWithDebInfo - optimized with debug symbols
#                            MinSizeRel     - for min size optimized library
#
# Top-level directory in which to install library and include files e.g.
#
# -D CMAKE_INSTALL_PREFIX=/path/to/install/into
#
# The easiest way to specify paths to TPLs (Third-party libraries) used by
# MSTK is to use
#
# -D CMAKE_PREFIX_PATH="path/to/dir1;path/to/dir2;path/to/dir3"
#
# If you want much more fine grained control on where packages are picked up
# from, each dependency has a PkgName_DIR variable that can be specified
#
# If Parallelism is enabled, you must use Metis or Zoltan as a
# partitioner (specify at least one) If Metis is enabled, it will
# assume that the metis version is 5 or greater library you are
# linking to. The path to METIS can be specified in CMAKE_PREFIX_PATH
# or using METIS_DIR. The path to Zoltan can be specified in
# CMAKE_PREFIX_PATH or using Zoltan_DIR
#
# -D ENABLE_METIS=yes|no  (default=no)
# -D ENABLE_ZOLTAN=yes|no (default=no)
#
# Support for importing/exporting ExodusII file
#
# -D ENABLE_ExodusII=yes|no (default=yes)
#
# Must define path to ExodusII and NetCDF packages in CMAKE_PREFIX_PATH or 
# in the following way
# 
# -D ExodusII_DIR:FILEPATH="/usr/packages/exodusii/"
# -D NetCDF_DIR:FILEPATH="/usr/packages/netcdf-4.0/"
#
#
# -D ENABLE_Tests=yes|no (default=yes)
#
# If tests are enabled then path to UnitTest++ has to be specified
#
# Rao Garimella (rao@lanl.gov)


# Top level directory where the code lives

SOURCE=$HOME/develop/mstk/dev

# Clear out old junk

rm -fr CMake* *.cmake Make*

# Simple specification of cmake command

cmake \
    -D CMAKE_BUILD_TYPE:STRING=Debug \
    -D CMAKE_PREFIX_PATH="/path/to/tpl/dir1;/path/to/tpl/dir2;/path/to/tpl/dir3" \
    -D CMAKE_INSTALL_PREFIX:FILEPATH=/where/you/want/to/install/mstk \
    -D ENABLE_PARALLEL=yes \
    -D ENABLE_ZOLTAN=yes \
    -D ENABLE_METIS=yes \
    -D ENABLE_ExodusII=yes \
    -D ENABLE_Tests=yes \
    ${SOURCE}


# Alternate fine-grained command that controls the paths to individual libs

cmake \
    -D CMAKE_BUILD_TYPE:STRING=Debug \
    -D CMAKE_INSTALL_PREFIX=/where/you/want/to/install/mstk \
    -D ENABLE_PARALLEL=yes \
    -D ENABLE_ZOLTAN=yes \
    -D ENABLE_METIS=yes \
    -D ENABLE_ExodusII=yes \
    -D NetCDF_DIR:FILEPATH=/path/to/netCDF/dir \
    -D ExodusII_DIR:FILEPATH=/path/to/ExodusII/dir \
    -D METIS_DIR:FILEPATH=/path/to/METIS/dir \
    -D ZOLTAN_DIR:FILEPATH=/path/to/Zoltan/dir \
    -D ParMETIS_DIR:FILEPATH=/path/to/parmetis/dir/if/zoltan/needs/it \
    -D PTScotch_DIR:FILEPATH=/path/to/ptscotch/dir/if/zoltan/needs/it \
    -D ENABLE_Tests=yes \
    -D UnitTest_DIR:FILEPATH=/path/to/UnitTest++/dir \
    ${SOURCE} 

