#!/bin/bash

#
# Driver file for building MSTK
# 
# -D CMAKE_BUILD_TYPE:STRING=Debug          - for debug library
#                            Release        - for optimized library
#                            RelWithDebInfo - optimized with debug symbols
#                            MinSizeRel     - for min size optimized library
#
# Top-level directory in which to install library and include files e.g.
#
# -D INSTALL_DIR:FILEPATH=/usr/local/packages
#
# Use Metis or Zoltan as a partitioner (specify at least one)
# If Metis is enabled, it will assume that the metis version is 5 or greater
# If you want to link to an older version of Metis, you must also specify
# -D METIS_MAJOR_VERSION=4 or whatever the major version is of the Metis
# library you are linking to. The path to METIS can be specified in
# CMAKE_PREFIX_PATH or using METIS_DIR. The path to Zoltan can be specified
# in CMAKE_PREFIX_PATH or using Zoltan_DIR
#
# -D ENABLE_METIS=yes|no  (default=no)
# -D ENABLE_ZOLTAN=yes|no (default=no)
#
# Support for importing/exporting ExodusII file
#
# -D ENABLE_ExodusII=yes|no (default=yes)
#
# Must define path to ExodusII and NetCDF packages in CMAKE_PREFIX_PATH or 
# in the following way
# 
# -D ExodusII_DIR:FILEPATH="/usr/packages/exodusii/"
# -D NetCDF_DIR:FILEPATH="/usr/packages/netcdf-4.0/"
#
#
# -D ENABLE_Tests=yes|no (default=yes)
#
# If tests are enabled then path to UnitTest++ has to be specified
#
# Rao Garimella (rao@lanl.gov)



# Define platform 

ARCH=`uname -m`
OS=`uname -s`
ARCHOS=${ARCH}_${OS}


# Top level directory where the code lives

SOURCE=$HOME/develop/mstk/dev



# Clear out old junk

rm -f CMakeCache.txt
rm -f cmake_install.cmake
rm -fr CMakefiles/
rm -f CTestTestfile.cmake
rm -f MSTKConfig.cmake
rm -fr Makefile


# modify the paths that point to the location of the
# installation directories below

cmake \
  -D CMAKE_BUILD_TYPE:STRING=Debug \
  -D ENABLE_PARALLEL=yes \
  -D ENABLE_ZOLTAN=yes \
  -D ENABLE_METIS=yes \
  -D ENABLE_ExodusII=yes \
  -D NetCDF_DIR:FILEPATH=/research/rao/ascem-tpl \
  -D ExodusII_DIR:FILEPATH=/research/rao/ascem-tpl \
  -D METIS_DIR:FILEPATH=/research/rao/ascem-tpl/metis-4.0.3 \
  -D ZOLTAN_DIR:FILEPATH=/research/rao/ascem-tpl/trilinos-11.0.3 \
  -D ENABLE_Tests=yes \
  -D UnitTest_DIR:FILEPATH=/research/rao/ascem-tpl \
  -D INSTALL_DIR:FILEPATH=${SOURCE} \
  ${SOURCE} 

# Alternate specification of cmake command

cmake \
  -D CMAKE_BUILD_TYPE:STRING=Debug \
  -D CMAKE_PREFIX_PATH="/research/rao/ascem-tpl;/research/rao/ascem-tpl/metis-4.0.3;/research/rao/ascem-tpl/trilinos-11.0.3" \
  -D ENABLE_PARALLEL=yes \
  -D ENABLE_ZOLTAN=yes \
  -D ENABLE_METIS=yes \
  -D ENABLE_ExodusII=yes \
  -D ENABLE_Tests=yes \
  -D INSTALL_DIR:FILEPATH=${SOURCE} \
  ${SOURCE}

